"""delete feature for customer

Revision ID: 2af9cbfadddc
Revises: 3316dc894834
Create Date: 2024-07-10 18:42:59.061812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af9cbfadddc'
down_revision = '3316dc894834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('c_ID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('transaction_c_ID_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['c_ID'], ['c_ID'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_c_ID_fkey', 'customer', ['c_ID'], ['c_ID'])
        batch_op.alter_column('c_ID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
