"""added pwd to staff table  

Revision ID: 606db41e90c7
Revises: cb2d19dad5d7
Create Date: 2024-07-09 12:35:35.589191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606db41e90c7'
down_revision = 'cb2d19dad5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('s_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('s_password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
