"""added category to Item

Revision ID: 845bbdd6b22e
Revises: 2af9cbfadddc
Create Date: 2024-07-18 13:26:48.133365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845bbdd6b22e'
down_revision = '2af9cbfadddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventoryitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Item_category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventoryitem', schema=None) as batch_op:
        batch_op.drop_column('Item_category')

    # ### end Alembic commands ###
